name: AtomX kernel Builder

on: 
  push:
    branches:
      - main

  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: atomxorg/archlinux:latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Building lisa Kernel
      env:
        BOT_API_KEY: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }} 
      run: |
        - cd /drone/src
        wget https://raw.githubusercontent.com/skyhuppa/AtomX-Kernel-Builder/master/Setup.sh
        bash AtomX.sh
