name: Lisa Kernel

on: 
  push:
    branches:
      - kernel.lnx.5.4.r1-rel/main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: jprimero15/archlinux-docker:latest

    steps:
    - uses: actions/checkout@v3
    - name: Building lisa Kernel
      env:
        BOT_API_KEY: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }} 
      run: |
            bash Setup.sh
            bash AtomX.sh

